# Generated by Django 2.0 on 2017-12-29 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='log',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
