# Generated by Django 2.0 on 2018-01-07 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='avatar_profile',
        ),
    ]
